services:
  db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_DB: giscademy
      POSTGRES_USER: giscademy_user
      POSTGRES_PASSWORD: giscademy_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    # 'ports' er valgfritt for DB, men fint for enkel tilgang
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"   # <- Viktig: publiser porten på verten

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"   # <- Viktig: publiser porten på verten

volumes:
  pgdata:
